<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<meta name="google-site-verification" content="ulechw5XJLBdsR0-4CvLMjRr3KXOT0jyLZNTEhzE80U" />
	<title></title>
	<script type="text/javascript">
        function click() {
            window.open('/index/auth', 'Auth', 'height=600,width=600,status=no,toolbar=no,menubar=no,location=no, resizable=no');
        }
	</script>
</head>
<body>
	<?php if (!$this->auth):?>
	   <a href="#" onclick="click();return false;">Login</a>
	<?php else:?>
	   <a href="/index/logout" onclick="">Logout</a>
	<?php endif;?>
	<?php Zend_Debug::dump($this->twitterId);?>
	<?php Zend_Debug::dump($this->twitterParam);?>
</body>
</html>