<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<meta name="google-site-verification" content="ulechw5XJLBdsR0-4CvLMjRr3KXOT0jyLZNTEhzE80U" />
	<title></title>
	<script type="text/javascript">
        function login(by) {
            by =  by || 'google';
            window.open('/index/auth/by/' + by, 'Auth', 'height=600,width=600,status=no,toolbar=no,menubar=no,location=no, resizable=no');
        }
	</script>
</head>
<body>
	<?php if (!$this->isAuth):?>
	   <a href="#" onclick="login('google');return false;">Login with Google</a>
	   <a href="#" onclick="login('twitter');return false;">Login with Twitter</a>
	<?php else:?>
	   <a href="/index/logout" onclick="">Logout</a>
	   <div>ID: <?php echo $this->id;?></div>
	<?php endif;?>
</body>
</html>