<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <!-- Google site verification-->
    <meta name="google-site-verification" content="ulechw5XJLBdsR0-4CvLMjRr3KXOT0jyLZNTEhzE80U" />
    <!-- Vkontakte Open api-->
    <script src="http://vkontakte.ru/js/api/openapi.js" type="text/javascript"></script>
    <script type="text/javascript">
        VK.init({
            apiId: <?php echo $this->vkAppId;?>

        });
    </script>
    <title>Social Auth</title>
    <script type="text/javascript">
        function login(by) {
            by =  by || 'google';
            if (by == 'vkontakte') {
                VK.Auth.login(function(response) {
                    if (response.session) {
                        var exdate = new Date();
                        exdate.setMinutes(exdate.getMinutes() + 10);
                        var user = response.session.user;
                        var cookie = 'vk_user_info_' + <?php echo $this->vkAppId;?> +'=';
                        for (key in user) {
                            cookie += key + '=' + escape(user[key]) + '&';
                        }
                        cookie += '; expires=' + exdate.toUTCString();
                        document.cookie = cookie;
                        document.location = '<?php echo $this->vkAuthUrl;?>';
                    } else {
                    }
                });
            } else {
                window.open('<?php echo $this->siteDir;?>/index/auth/by/' + by, 'Auth', 'height=600,width=600,status=no,toolbar=no,menubar=no,location=no, resizable=no');
            }
        }
    </script>
    <style type="text/css">
       a, img {border: none;}
    </style>
</head>
<body>
    <?php if (!$this->auth):?>
       <h1>Login via:</h1>
       <a href="#" onclick="login('google');return false;"><img alt="google" src="<?php echo $this->siteDir;?>/img/google.png" /></a>
       <a href="#" onclick="login('twitter');return false;"><img alt="twitter" src="<?php echo $this->siteDir;?>/img/twitter.png" /></a>
       <a href="#" onclick="login('facebook');return false;"><img alt="facebook" src="<?php echo $this->siteDir;?>/img/facebook.png" /></a>
       <a href="#" onclick="login('vkontakte');return false;"><img alt="vkontakte" src="<?php echo $this->siteDir;?>/img/vkontakte.png" /></a>
       <a href="#" onclick="login('mailru');return false;"><img alt="mailru" src="<?php echo $this->siteDir;?>/img/mailru.png" /></a>
       <a href="#" onclick="login('foursquare');return false;"><img alt="foursquare" src="<?php echo $this->siteDir;?>/img/foursquare.png" /></a>
       <a href="#" onclick="login('flickr');return false;"><img alt="flickr" src="<?php echo $this->siteDir;?>/img/flickr.png" /></a>
       <a href="#" onclick="login('gowalla');return false;"><img alt="gowalla" src="<?php echo $this->siteDir;?>/img/gowalla.png" /></a>
    <?php else:?>
       <a href="<?php echo $this->siteDir;?>/index/logout" onclick="">Logout</a>
       <div><strong>Parameters:</strong><pre> <?php print_r($this->parameters);?></pre></div>
    <?php endif;?>
</body>
</html>