<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <!-- Google site verification-->
    <meta name="google-site-verification" content="ulechw5XJLBdsR0-4CvLMjRr3KXOT0jyLZNTEhzE80U" />
    <title>Social Auth</title>
    <script type="text/javascript">
        function login(by) {
            by =  by || 'google';
            window.open('<?php echo $this->baseUrl();?>/index/auth/by/' + by, 'Auth', 'height=600,width=600,status=no,toolbar=no,menubar=no,location=no, resizable=no');
        }
    </script>
    <style type="text/css">
       a, img {border: none;}
    </style>
</head>
<body>
    <?php if (!$this->auth):?>
       <h1>Login via:</h1>
       <a href="#" onclick="login('google');return false;"><img alt="google" src="<?php echo $this->baseUrl();?>/img/google.png" /></a>
       <a href="#" onclick="login('twitter');return false;"><img alt="twitter" src="<?php echo $this->baseUrl();?>/img/twitter.png" /></a>
       <a href="#" onclick="login('facebook');return false;"><img alt="facebook" src="<?php echo $this->baseUrl();?>/img/facebook.png" /></a>
       <a href="#" onclick="login('vkontakte');return false;"><img alt="vkontakte" src="<?php echo $this->baseUrl();?>/img/vkontakte.png" /></a>
       <a href="#" onclick="login('mailru');return false;"><img alt="mailru" src="<?php echo $this->baseUrl();?>/img/mailru.png" /></a>
       <a href="#" onclick="login('foursquare');return false;"><img alt="foursquare" src="<?php echo $this->baseUrl();?>/img/foursquare.png" /></a>
       <a href="#" onclick="login('flickr');return false;"><img alt="flickr" src="<?php echo $this->baseUrl();?>/img/flickr.png" /></a>
       <a href="#" onclick="login('gowalla');return false;"><img alt="gowalla" src="<?php echo $this->baseUrl();?>/img/gowalla.png" /></a>
       <a href="#" onclick="login('github');return false;"><img alt="github" src="<?php echo $this->baseUrl();?>/img/github.png" /></a>
    <?php else:?>
       <a href="<?php echo $this->baseUrl();?>/index/logout" onclick="">Logout</a>
       <div><strong>Parameters:</strong><pre> <?php print_r($this->userData);?></pre></div>
    <?php endif;?>
</body>
</html>